### ISSUE TITLE
NJR to find correct links for missing 

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/fieldnotes#10]
related to #6 

Greg's instructions:
>Here is the spreadsheet detailing which pages in the field notes wiki appear to be missing (i.e. broken links).
https://github.com/cu-mkp/fieldnotes/blob/main/missing.csv
The information here are the filenames of the page where the missing file was linked, and the name of the missing file itself.
Note that these file names are also the URLs, so you should be able to copy-paste them with the prefix "http://fieldnotes.makingandknowing.org/mainSpace/" and it will work.

>If you manage to locate any of these missing files, you can add the name of the missing file as it appears here and the corrected name to the corrections spreadsheet:
https://github.com/cu-mkp/fieldnotes/blob/main/corrections.csv

>The "missing.csv" spreadsheet is automatically generated, so any edits on it will be overwritten.
The "corrections.csv" spreadsheet is created manually, but it is very important that you edit it as a CSV and remain conscious of special unicode characters. To this end, it is probably best if you simply copy-paste the HTML-quoted URL or unquoted filename into the spreadsheet rather than typing it out manually, because sometimes seemingly-innocuous spaces are not as they appear...

>Once the missing files have been accounted for to our satisfaction or simply ignored, I can get started on moving the files into their new directory structure.

NJR is tracking the full URLs (due to S3 problems noted in #9) in the GD sheet, [fieldnotes_20210507_missing](https://docs.google.com/spreadsheets/d/1Adj1h9BOhBQuQdkdYP-R_gbBkx7NZ6W4fpToyjmUg8A/edit#gid=0)

**Comment by njr2128** [comment]
Ones that could not be found in this round of "missing"
created a local copy to track for myself: [missing - Copy.xlsx](https://github.com/cu-mkp/fieldnotes/files/6442435/missing.-.Copy.xlsx)

[parent] [file]
- Nisse, Cleo 2.html Verdigris Cleo.html

**Comment by gschare** [comment]
See #11.
Closing with some files still missing, to be revisited in a future issue.
